name: webct
channels:
  - conda-forge
  - ccpi
  - https://software.repos.intel.com/python/conda
  - astra-toolbox
dependencies:
  - python>=3.11.9

  # use (smaller, better, faster, stronger) open-source BLAS libraries to avoid
  # massive bloatware and license infringements from mkl used by default numpy
  - conda-forge::blas=*=openblas

  # Runtime
  - flask
  - scipy
  - matplotlib
  - opencv
  - cil>=24.3.0
  - tigre
  - astra-toolbox
  - ccpi-regulariser
  - py-cpuinfo

  # Packaging
  - pyinstaller

  # Development linting and testing
  - ruff
  - pytest
  - pytest-cov

  # Building 'xpecgen' and 'spekpy' using the legacy setup.py bdist_wheel
  # mechanism, which will be removed in a future version. pip 25.3 will enforce
  # this behaviour change. Discussion can be found at
  # https://github.com/pypa/pip/issues/6334
  - pip<25.3

  # Pip packages
  # (environment.yml does not support multiple pip: keys.)
  - pip:
    # Runtime
    - gvxr
    - json5
    - imageio[ffmpeg]
    - git+https://bitbucket.org/spekpy/spekpy_release.git
    # - git+https://github.com/kylechampley/XrayPhysics
    - xpecgen
